# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mikolaj/Desktop/cuda-voxel-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mikolaj/Desktop/cuda-voxel-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikolaj/Desktop/cuda-voxel-engine/CMakeFiles /home/mikolaj/Desktop/cuda-voxel-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikolaj/Desktop/cuda-voxel-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scve

# Build rule for target.
scve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scve
.PHONY : scve

# fast build rule for target.
scve/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/build
.PHONY : scve/fast

#=============================================================================
# Target rules for targets named mandelbulb

# Build rule for target.
mandelbulb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mandelbulb
.PHONY : mandelbulb

# fast build rule for target.
mandelbulb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbulb.dir/build.make CMakeFiles/mandelbulb.dir/build
.PHONY : mandelbulb/fast

examples/mandelbulb.o: examples/mandelbulb.cu.o
.PHONY : examples/mandelbulb.o

# target to build an object file
examples/mandelbulb.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbulb.dir/build.make CMakeFiles/mandelbulb.dir/examples/mandelbulb.cu.o
.PHONY : examples/mandelbulb.cu.o

examples/mandelbulb.i: examples/mandelbulb.cu.i
.PHONY : examples/mandelbulb.i

# target to preprocess a source file
examples/mandelbulb.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbulb.dir/build.make CMakeFiles/mandelbulb.dir/examples/mandelbulb.cu.i
.PHONY : examples/mandelbulb.cu.i

examples/mandelbulb.s: examples/mandelbulb.cu.s
.PHONY : examples/mandelbulb.s

# target to generate assembly for a file
examples/mandelbulb.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mandelbulb.dir/build.make CMakeFiles/mandelbulb.dir/examples/mandelbulb.cu.s
.PHONY : examples/mandelbulb.cu.s

src/block_variant/block_texture.o: src/block_variant/block_texture.cu.o
.PHONY : src/block_variant/block_texture.o

# target to build an object file
src/block_variant/block_texture.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_texture.cu.o
.PHONY : src/block_variant/block_texture.cu.o

src/block_variant/block_texture.i: src/block_variant/block_texture.cu.i
.PHONY : src/block_variant/block_texture.i

# target to preprocess a source file
src/block_variant/block_texture.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_texture.cu.i
.PHONY : src/block_variant/block_texture.cu.i

src/block_variant/block_texture.s: src/block_variant/block_texture.cu.s
.PHONY : src/block_variant/block_texture.s

# target to generate assembly for a file
src/block_variant/block_texture.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_texture.cu.s
.PHONY : src/block_variant/block_texture.cu.s

src/block_variant/block_variant_manager.o: src/block_variant/block_variant_manager.cu.o
.PHONY : src/block_variant/block_variant_manager.o

# target to build an object file
src/block_variant/block_variant_manager.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_variant_manager.cu.o
.PHONY : src/block_variant/block_variant_manager.cu.o

src/block_variant/block_variant_manager.i: src/block_variant/block_variant_manager.cu.i
.PHONY : src/block_variant/block_variant_manager.i

# target to preprocess a source file
src/block_variant/block_variant_manager.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_variant_manager.cu.i
.PHONY : src/block_variant/block_variant_manager.cu.i

src/block_variant/block_variant_manager.s: src/block_variant/block_variant_manager.cu.s
.PHONY : src/block_variant/block_variant_manager.s

# target to generate assembly for a file
src/block_variant/block_variant_manager.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/block_variant/block_variant_manager.cu.s
.PHONY : src/block_variant/block_variant_manager.cu.s

src/light/point_light_manager.o: src/light/point_light_manager.cu.o
.PHONY : src/light/point_light_manager.o

# target to build an object file
src/light/point_light_manager.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/light/point_light_manager.cu.o
.PHONY : src/light/point_light_manager.cu.o

src/light/point_light_manager.i: src/light/point_light_manager.cu.i
.PHONY : src/light/point_light_manager.i

# target to preprocess a source file
src/light/point_light_manager.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/light/point_light_manager.cu.i
.PHONY : src/light/point_light_manager.cu.i

src/light/point_light_manager.s: src/light/point_light_manager.cu.s
.PHONY : src/light/point_light_manager.s

# target to generate assembly for a file
src/light/point_light_manager.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/light/point_light_manager.cu.s
.PHONY : src/light/point_light_manager.cu.s

src/octree/octree.o: src/octree/octree.cu.o
.PHONY : src/octree/octree.o

# target to build an object file
src/octree/octree.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree.cu.o
.PHONY : src/octree/octree.cu.o

src/octree/octree.i: src/octree/octree.cu.i
.PHONY : src/octree/octree.i

# target to preprocess a source file
src/octree/octree.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree.cu.i
.PHONY : src/octree/octree.cu.i

src/octree/octree.s: src/octree/octree.cu.s
.PHONY : src/octree/octree.s

# target to generate assembly for a file
src/octree/octree.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree.cu.s
.PHONY : src/octree/octree.cu.s

src/octree/octree_utils.o: src/octree/octree_utils.cu.o
.PHONY : src/octree/octree_utils.o

# target to build an object file
src/octree/octree_utils.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree_utils.cu.o
.PHONY : src/octree/octree_utils.cu.o

src/octree/octree_utils.i: src/octree/octree_utils.cu.i
.PHONY : src/octree/octree_utils.i

# target to preprocess a source file
src/octree/octree_utils.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree_utils.cu.i
.PHONY : src/octree/octree_utils.cu.i

src/octree/octree_utils.s: src/octree/octree_utils.cu.s
.PHONY : src/octree/octree_utils.s

# target to generate assembly for a file
src/octree/octree_utils.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/octree/octree_utils.cu.s
.PHONY : src/octree/octree_utils.cu.s

src/renderer/cuda_renderer.o: src/renderer/cuda_renderer.cu.o
.PHONY : src/renderer/cuda_renderer.o

# target to build an object file
src/renderer/cuda_renderer.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer.cu.o
.PHONY : src/renderer/cuda_renderer.cu.o

src/renderer/cuda_renderer.i: src/renderer/cuda_renderer.cu.i
.PHONY : src/renderer/cuda_renderer.i

# target to preprocess a source file
src/renderer/cuda_renderer.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer.cu.i
.PHONY : src/renderer/cuda_renderer.cu.i

src/renderer/cuda_renderer.s: src/renderer/cuda_renderer.cu.s
.PHONY : src/renderer/cuda_renderer.s

# target to generate assembly for a file
src/renderer/cuda_renderer.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer.cu.s
.PHONY : src/renderer/cuda_renderer.cu.s

src/renderer/cuda_renderer_utils.o: src/renderer/cuda_renderer_utils.cu.o
.PHONY : src/renderer/cuda_renderer_utils.o

# target to build an object file
src/renderer/cuda_renderer_utils.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer_utils.cu.o
.PHONY : src/renderer/cuda_renderer_utils.cu.o

src/renderer/cuda_renderer_utils.i: src/renderer/cuda_renderer_utils.cu.i
.PHONY : src/renderer/cuda_renderer_utils.i

# target to preprocess a source file
src/renderer/cuda_renderer_utils.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer_utils.cu.i
.PHONY : src/renderer/cuda_renderer_utils.cu.i

src/renderer/cuda_renderer_utils.s: src/renderer/cuda_renderer_utils.cu.s
.PHONY : src/renderer/cuda_renderer_utils.s

# target to generate assembly for a file
src/renderer/cuda_renderer_utils.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/renderer/cuda_renderer_utils.cu.s
.PHONY : src/renderer/cuda_renderer_utils.cu.s

src/vector3.o: src/vector3.cu.o
.PHONY : src/vector3.o

# target to build an object file
src/vector3.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/vector3.cu.o
.PHONY : src/vector3.cu.o

src/vector3.i: src/vector3.cu.i
.PHONY : src/vector3.i

# target to preprocess a source file
src/vector3.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/vector3.cu.i
.PHONY : src/vector3.cu.i

src/vector3.s: src/vector3.cu.s
.PHONY : src/vector3.s

# target to generate assembly for a file
src/vector3.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/vector3.cu.s
.PHONY : src/vector3.cu.s

src/voxel_engine.o: src/voxel_engine.cu.o
.PHONY : src/voxel_engine.o

# target to build an object file
src/voxel_engine.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/voxel_engine.cu.o
.PHONY : src/voxel_engine.cu.o

src/voxel_engine.i: src/voxel_engine.cu.i
.PHONY : src/voxel_engine.i

# target to preprocess a source file
src/voxel_engine.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/voxel_engine.cu.i
.PHONY : src/voxel_engine.cu.i

src/voxel_engine.s: src/voxel_engine.cu.s
.PHONY : src/voxel_engine.s

# target to generate assembly for a file
src/voxel_engine.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scve.dir/build.make CMakeFiles/scve.dir/src/voxel_engine.cu.s
.PHONY : src/voxel_engine.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mandelbulb"
	@echo "... scve"
	@echo "... examples/mandelbulb.o"
	@echo "... examples/mandelbulb.i"
	@echo "... examples/mandelbulb.s"
	@echo "... src/block_variant/block_texture.o"
	@echo "... src/block_variant/block_texture.i"
	@echo "... src/block_variant/block_texture.s"
	@echo "... src/block_variant/block_variant_manager.o"
	@echo "... src/block_variant/block_variant_manager.i"
	@echo "... src/block_variant/block_variant_manager.s"
	@echo "... src/light/point_light_manager.o"
	@echo "... src/light/point_light_manager.i"
	@echo "... src/light/point_light_manager.s"
	@echo "... src/octree/octree.o"
	@echo "... src/octree/octree.i"
	@echo "... src/octree/octree.s"
	@echo "... src/octree/octree_utils.o"
	@echo "... src/octree/octree_utils.i"
	@echo "... src/octree/octree_utils.s"
	@echo "... src/renderer/cuda_renderer.o"
	@echo "... src/renderer/cuda_renderer.i"
	@echo "... src/renderer/cuda_renderer.s"
	@echo "... src/renderer/cuda_renderer_utils.o"
	@echo "... src/renderer/cuda_renderer_utils.i"
	@echo "... src/renderer/cuda_renderer_utils.s"
	@echo "... src/vector3.o"
	@echo "... src/vector3.i"
	@echo "... src/vector3.s"
	@echo "... src/voxel_engine.o"
	@echo "... src/voxel_engine.i"
	@echo "... src/voxel_engine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

